### PR TITLE
Include build in the project

### PR DESCRIPTION
**Pull request by tomek-he-him**
I believe this belongs to the project as well.

### CODE REVIEW

**Comment by tomek-he-him** [comment]
Ready to merge :)

I should have written the gulpfile in coffeescript from the very beginning.

With e040739 we'll be sure to check in freshly-built files any time we make a commit.

**Comment by tomek-he-him** [comment]
:bell: is there anything I can do to help push this and other PRs forward?

**Comment by tomek-he-him** [comment]
I'm now starting to need these changes – so I'll wait with submitting new PRs until you review and merge these. I don't want to trash new PRs with commits that belong here.

**Comment by DanielHoffmann** [comment]
By day I (unfortunately) am a Java/Maven developer so I only play around in my own free time with the node stack, so I am not familiar with all the build architecture needed to properly maintain a node package. As such it might take me some time to get around testing this. I really did not think people would be interested in my plugin so I only added a bower file.

Nevertheless making a proper node package is a good thing, I will look into it. If you plan to actually completely remove the jQuery dependency I recommend you fork my project for now and develop in another repo (well at least the repo name would need to change anyway to not start with jQuery).

**Comment by tomek-he-him** [comment]
Closing to remove clutter 🙂

Feel free to reopen if you think this is mergeable.

**Pull request closed without merging**
